# Generated by Django 4.2.1 on 2023-06-15 15:40

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(validators=[blog.validators.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(validators=[blog.validators.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[blog.validators.validate_not_empty]),
        ),
    ]
