# Generated by Django 4.2.1 on 2023-06-21 17:56

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[blog.validators.validate_not_empty], verbose_name='Заголовок'),
        ),
    ]
